### ISSUE TITLE
résolution d'issue impossible

### ISSUE THREAD

**Issue by loicrochet** [BioDataScience-Course/sdd-umons-2023#2]
Bonjour @phgrosjean ,
Je n'arrive pas à résoudre une issue et cela m'empêche de faire les pulls pour pouvoir continuer mon projet de groupe. Voici le message d'erreur qui apparait ainsi que les modifications apportées au document :

![image](https://github.com/BioDataScience-Course/sdd-umons-2023/assets/145350399/ff1059e8-cd3f-4f6f-9842-3f964247f288)

**Comment by phgrosjean** [comment]
@loicrochet Les mots importants sont à la fin du message : vous avez un conflit non résolu. Il faut résoudre cela en priorité, ensuite la personne qui résoudra le conflit (je pense malheureusement que c'est tombé sur ta pomme !) doit faire un commit du fichier corrigé, ensuite un nouveau pull et un push... et tous les autres font des pulls pour se synchroniser.

Dans l'onglet Git, le ou les fichiers où il y a conflit apparaissent avec une icône "U" orange.

Évitez autant que possible d'éditer à plusieurs la même partie du document.
