### ISSUE TITLE
Projet de groupe

### ISSUE THREAD

**Issue by loicrochet** [BioDataScience-Course/sdd-umons-2023#3]
@phgrosjean pour la fin du projet de groupe commencé en début d'année, faut-il faire un tableau de contingence à simple entrée et un tableau de contingence à double entrée pour l'ensemble du groupe ou bien un de chaque par membre du groupe ?

**Comment by phgrosjean** [comment]
@loicrochet Faites si possible un tableau de contingence à simple et double entrée par étudiant. Mais selon les données, cela n'est pas toujours possible. Faites pour un mieux.

Sinon, tu postes tes issues dans le dépôt sdd-umons-2023 qui est le dépôt du cours en ligne. Il faut poster dans https://github.com/BioDataScience-Course/A00qa_23M_issues-a23/issues

**Comment by loicrochet** [comment]
d'accord merci beaucoup
